version: "3.7"

services:
  unpubdev:
    container_name: unpudev
    image: printeastwoodcz/unpubdev
    restart: always
    volumes:
      - unpubdev_storage:/app/${UNPUBDEV_FOLDER}
    ports:
      - 14000:4000
    environment:
      UNPUBDEV_MONGO_STRING: ${UNPUBDEV_MONGO_STRING}
      UNPUBDEV_HOST: ${UNPUBDEV_HOST}
      UNPUBDEV_PORT: ${UNPUBDEV_PORT}
      UNPUBDEV_FOLDER: ${UNPUBDEV_FOLDER}
      UNPUBDEV_PROXY_ORIGIN: ${UNPUBDEV_PROXY_ORIGIN}
      UNPUBDEV_PACKAGE_PREFIX: ${UNPUBDEV_PACKAGE_PREFIX}
      UNPUBDEV_EMAIL_DOMAIN: ${UNPUBDEV_EMAIL_DOMAIN}
      UNPUBDEV_STORAGE: ${UNPUBDEV_STORAGE}

volumes:
  unpubdev_storage: {}
