version: "3.7"

services:
  mongodb:
    container_name: unpubdev_mongodb
    image: mongo:5.0
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongo_storage:/data/db
      - "./mongo-entrypoint/:/docker-entrypoint-initdb.d/"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ADMIN_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ADMIN_PASSWORD}
      MONGO_UNPUBDEV_USERNAME: ${MONGO_UNPUBDEV_USERNAME}
      MONGO_UNPUBDEV_PASSWORD: ${MONGO_UNPUBDEV_PASSWORD}
      MONGO_DB: ${MONGO_DB}
    command: [--auth]
  unpubdev:
    container_name: unpudev
    image: printeastwoodcz/unpubdev:1.0.5-dev.3
    restart: always
    volumes:
      - unpubdev_storage:/app/unpubdev-packages
    ports:
      - 14000:4000
    links:
      - mongodb
    depends_on:
      - mongodb
    environment:
      DB_URL: mongodb://${MONGO_UNPUBDEV_USERNAME}:${MONGO_UNPUBDEV_PASSWORD}@mongodb:27017
      WAIT_HOSTS: mongodb:27017

volumes:
  minio_storage: {}
  mongo_storage: {}
  unpubdev_storage: {}
