version: "3.7"

services:
  mongodb:
    image: mongo:5.0.17
    ports:
      - "27017:27017"
    restart: always
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: masoud
      MINIO_ROOT_PASSWORD: Strong#Pass#2022
    command: server --console-address ":9001" /data
  unpubdev:
    container_name: unpudev
    image: printeastwoodcz/upubdev:1.0.0
    restart: always
    volumes:
      - .:/app
    ports:
      - 4000:4000
    links:
      - mongodb
      - minio
    depends_on:
      - mongodb
      - minio
    environment:
      DB_URL: mongodb://mongodb:27017/pub
      WAIT_HOSTS: mongodb:27017, minio:9000

volumes:
  minio_storage: {}
