version: "3.7"

services:
  minio:
    container_name: unpubdev_minio
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    command: server --console-address ":9001" /data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://minio:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
  createbuckets:
    container_name: unpubdev_minio_mc
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};
      /usr/bin/mc mb myminio/${MINIO_BUCKET_NAME};
      /usr/bin/mc anonymous set public myminio/${MINIO_BUCKET_NAME};
      echo 'my content' > myfile.txt;
      /usr/bin/mc cp myfile.txt myminio/${MINIO_BUCKET_NAME};
      exit 0;
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://minio:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  mongodb:
    container_name: unpubdev_mongodb
    image: mongo:5.0.17
    ports:
      - "27017:27017"
    restart: unless-stopped
    volumes:
      - mongo_storage:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
  unpubdev:
    container_name: unpudev
    image: printeastwoodcz/unpubdev
    restart: always
    ports:
      - 4000:4000
    links:
      - mongodb
      - minio
    depends_on:
      - mongodb
      - minio
    environment:
      DB_URL: mongodb://mongodb:27017/unpubdev
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      WAIT_HOSTS: mongodb:27017, minio:9000

volumes:
  minio_storage: {}
  mongo_storage: {}
