version: "3.7"

services:
  unpubdev:
    container_name: unpudev
    image: printeastwoodcz/unpubdev:1.0.6
    restart: always
    volumes:
      - unpubdev_storage:/app/${UNPUBDEV_FOLDER}
    ports:
      - 14000:4000
    environment:
      DB_URL: ${UNPUBDEV_MONGO_STRING}
      UNPUBDEV_FOLDER: ${UNPUBDEV_FOLDER}

volumes:
  unpubdev_storage: {}
